### ISSUE TITLE
Hey :)

### ISSUE THREAD

**Issue by omid** [mb1986/actix-auth#1]
Hey Michał,

There is no way to contact you!

And my request is not even related to this project! :)

I want to ask you if you can create the PR regarding https://github.com/actix/actix-redis/pull/30

I think it's something that has to be merged and done.

**Comment by mb1986** [comment]
Hi Omid, sorry for so late response. Crazy time! Please correct me if I am wrong - you asked me to reopen the https://github.com/actix/actix-redis/pull/30 in the https://github.com/actix/actix-extras repository, didn't you?

**Comment by omid** [comment]
Hey, np, I hope everything is fine.
Yes, would be awesome and maybe sync with the master.
You did a great job, I think we should have it in actix.
